import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { document, init, ok, put, run, snapshot, temp } from "./helpers.mjs";

function pair(t) {
  const js = temp(t), py = temp(t);
  init(js);
  put(js, "src/main.js", "export const value = 1;\n");
  put(js, "docs/api/example.md", document());
  ok(run(js, ["index", "--write"]));
  fs.cpSync(path.join(js, "docs"), path.join(py, "docs"), { recursive: true });
  fs.copyFileSync(path.join(js, "okf.yml"), path.join(py, "okf.yml"));
  return [{ root: js, runtime: "node" }, { root: py, runtime: "python" }];
}
const invoke = (item, args) => run(item.root, args, { runtime: item.runtime });
const decisions = (out) => out.split("\n").filter((line) => /^cleanup (move|keep):/.test(line));

test("cleanup manifests, dry-run decisions and backup migration agree across runtimes", (t) => {
  const items = pair(t), checks = [];
  for (const item of items) {
    ok(invoke(item, ["render", "--output", "docs"]));
    put(item.root, "docs/manual.html", "<p>Handwritten output stays</p>\n");
    const edited = path.join(item.root, "docs/api/example.html");
    fs.appendFileSync(edited, "<!-- user edit -->\n");
    const before = snapshot(item.root);
    const out = ok(invoke(item, ["render", "--output", "_site", "--cleanup-from", "docs", "--check"]));
    checks.push(decisions(out));
    assert.deepEqual(snapshot(item.root), before);
    assert.equal(fs.existsSync(path.join(item.root, "_site")), false);
    assert.equal(fs.existsSync(path.join(item.root, ".okf/render-backups")), false);
    ok(invoke(item, ["render", "--output", "_site", "--cleanup-from", "docs"]));
    assert.equal(fs.readFileSync(path.join(item.root, "docs/manual.html"), "utf8"), before["docs/manual.html"]);
    assert.equal(fs.readFileSync(edited, "utf8"), before["docs/api/example.html"]);
    assert.equal(fs.existsSync(path.join(item.root, "docs/index.html")), false);
    const backupRoot = path.join(item.root, ".okf/render-backups");
    const backups = fs.readdirSync(backupRoot);
    assert.equal(backups.length, 1);
    assert.equal(fs.readFileSync(path.join(backupRoot, backups[0], "docs/index.html"), "utf8"), before["docs/index.html"]);
    // A rerun leaves the edited and untracked old files unchanged.
    ok(invoke(item, ["render", "--output", "_site", "--cleanup-from", "docs"]));
    assert.equal(fs.readFileSync(edited, "utf8"), before["docs/api/example.html"]);
    assert.deepEqual(fs.readdirSync(backupRoot), backups);
  }
  assert.deepEqual(checks[0], checks[1]);
  assert.deepEqual(snapshot(items[0].root, "_site"), snapshot(items[1].root, "_site"));
});

test("legacy cleanup accepts exact generated bytes and preserves unknown HTML in both runtimes", (t) => {
  const items = pair(t), checks = [];
  for (const item of items) {
    ok(invoke(item, ["render", "--output", "docs"]));
    fs.unlinkSync(path.join(item.root, "docs/.okf-render-manifest.json"));
    put(item.root, "docs/unknown.html", "<!-- okf-devkit-owned:v1 -->\n<p>Old or edited output</p>\n");
    checks.push(decisions(ok(invoke(item, ["render", "--output", "_site", "--cleanup-from", "docs", "--check"]))));
    ok(invoke(item, ["render", "--output", "_site", "--cleanup-from", "docs"]));
    assert.equal(fs.existsSync(path.join(item.root, "docs/index.html")), false);
    assert.equal(fs.existsSync(path.join(item.root, "docs/unknown.html")), true);
    assert.equal(fs.existsSync(path.join(item.root, "docs/api/example.md")), true);
  }
  assert.deepEqual(checks[0], checks[1]);
});

test("unsafe cleanup combinations fail before writing in both runtimes", (t) => {
  for (const item of pair(t)) {
    ok(invoke(item, ["render", "--output", "docs"]));
    fs.unlinkSync(path.join(item.root, "docs/.okf-render-manifest.json"));
    const before = snapshot(item.root, ".");
    const cases = [
      ["render", "--output", "docs", "--cleanup-from", "docs"],
      ["render", "--output", "docs/nested", "--cleanup-from", "docs"],
      ["render", "--cleanup-from", "../outside"],
      ["render", "--cleanup-from", "docs", "--hook"],
    ];
    if (process.platform === "win32") cases.push(
      ["render", "--output", "DOCS", "--cleanup-from", "docs"],
      ["render", "--output", "docs.", "--cleanup-from", "docs"],
      ["render", "--output", "_site", "--cleanup-from", "docs "],
      ["render", "--output", "DOCS/nested", "--cleanup-from", "docs"],
    );
    for (const args of cases) {
      assert.equal(invoke(item, [...args, "--check"]).status, 1, `${item.runtime}: ${args.join(" ")}`);
      assert.equal(invoke(item, args).status, 1, `${item.runtime}: ${args.join(" ")}`);
    }
    assert.deepEqual(snapshot(item.root, "."), before);
    assert.equal(fs.existsSync(path.join(item.root, "_site")), false);
  }
});
